# Generated by Django 3.1.6 on 2021-02-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='사용자 이름')),
                ('user_pw', models.CharField(max_length=64, verbose_name='사용자 비밀번호')),
                ('reg_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 일시')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
